/**
 * Regenerate sitemap.xml from the live Supabase package list.
 *
 * Static pages are listed below; package detail URLs are pulled from the
 * `packages` table so the sitemap never goes stale when you add a package
 * in the dashboard.
 *
 *   node tools/generate-sitemap.mjs
 *
 * Requires Node 18+ (uses the built-in fetch). No dependencies.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const SITE = 'https://luxpathtravel.com';

// Same anon key the public site already ships in assets/js/app.js — this is
// the read-only public key, safe to keep here.
const SUPABASE_URL = 'https://fgeeysssiesdlryoygoa.supabase.co';
const SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnZWV5c3NzaWVzZGxyeW95Z29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0MTI0MzUsImV4cCI6MjA5NTk4ODQzNX0.Sa3vcq9U2BrzFobTqQS4sAmVpXkRH09_PGzol9-NCvw';

/** Static pages: [path, changefreq, priority, withHreflang] */
const STATIC_PAGES = [
  ['/',                        'weekly',  '1.0', true],
  ['/بكج-شهر-عسل-بالي',        'weekly',  '0.9', true],
  ['/بكج-عائلي-اندونيسيا',      'weekly',  '0.9', true],
  ['/السياحة-في-بالي',          'monthly', '0.8', true],
  ['/بكجات-سياحية-اندونيسيا',   'weekly',  '0.9', true],
  ['/وجهات-السياحة-اندونيسيا',  'monthly', '0.7', true],
  ['/من-نحن',                  'monthly', '0.6', true],
  ['/تواصل',                   'monthly', '0.6', true],
  ['/الخصوصية',                'yearly',  '0.2', false],
];

const today = new Date().toISOString().slice(0, 10);

async function fetchPackageSlugs() {
  const url = `${SUPABASE_URL}/rest/v1/packages?select=slug_en,updated_at&is_active=eq.true`;
  const res = await fetch(url, {
    headers: { apikey: SUPABASE_ANON_KEY, Authorization: `Bearer ${SUPABASE_ANON_KEY}` },
  });
  if (!res.ok) throw new Error(`Supabase returned ${res.status} ${res.statusText}`);
  const rows = await res.json();
  return rows.filter(r => r.slug_en).map(r => ({
    slug: r.slug_en,
    lastmod: (r.updated_at || today).slice(0, 10),
  }));
}

function urlBlock({ loc, lastmod, changefreq, priority, hreflang }) {
  const alt = hreflang
    ? `\n    <xhtml:link rel="alternate" hreflang="ar" href="${loc}"/>` +
      `\n    <xhtml:link rel="alternate" hreflang="x-default" href="${loc}"/>`
    : '';
  return `  <url>
    <loc>${loc}</loc>${alt}
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}

async function main() {
  let packages = [];
  try {
    packages = await fetchPackageSlugs();
    console.log(`Fetched ${packages.length} active package(s) from Supabase.`);
  } catch (err) {
    console.error(`WARNING: could not reach Supabase (${err.message}).`);
    console.error('Writing sitemap with static pages only — package URLs omitted.');
  }

  const blocks = [
    ...STATIC_PAGES.map(([path, changefreq, priority, hreflang]) =>
      urlBlock({ loc: SITE + path, lastmod: today, changefreq, priority, hreflang })),
    ...packages.map(p =>
      urlBlock({
        loc: `${SITE}/بكج-سياحي-اندونيسيا?slug=${p.slug}`,
        lastmod: p.lastmod,
        changefreq: 'weekly',
        priority: '0.8',
        hreflang: false,
      })),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/generate-sitemap.mjs on ${today}. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">

${blocks.join('\n\n')}

</urlset>
`;

  const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'sitemap.xml');
  writeFileSync(out, xml, 'utf8');
  console.log(`Wrote ${blocks.length} URLs to sitemap.xml`);
}

main().catch(err => { console.error(err); process.exit(1); });
